require "bundler/gem_tasks"

require 'rspec/core'
require 'rspec/core/rake_task'

RSpec::Core::RakeTask.new(:spec) do |t|
  t.rspec_opts = ["-c", "-f progress", "-Ilib"]
  t.pattern = "spec/**/*_spec.rb"
  t.verbose = true
end
task :spec => :compile

require 'rake/extensiontask'
spec = eval File.read('asciipack.gemspec')
Rake::ExtensionTask.new('asciipack', spec) do |ext|
  ext.cross_compile = true
  ext.lib_dir = File.join(*['lib', 'asciipack', ENV['FAT_DIR']].compact)
end

task :default => [:spec]
